server:
  port: 8700

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/



spring:
  zipkin:
    base-url: http://localhost:9411

  application:
    name: zipkin-begin-server