server:
  port: 8768

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: zuul-server

zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: ribbon-server
    api-b:
      path: /api-b/**
      serviceId: feign-server